Repository coufit/coufit-back, pull requests merged in 2025-08, with the labels that each got.

#7 Feat: 소비 요약 대쉬보드 조회 API 구현
  src/main/java/goorm/coutfit/point/controller/PointController.java
  src/main/java/goorm/coutfit/point/controller/response/PointBalanceResponse.java
  src/main/java/goorm/coutfit/point/controller/response/PointSummaryResponse.java
  src/main/java/goorm/coutfit/point/repository/PaymentHistoryRepository.java
  src/main/java/goorm/coutfit/point/service/PointService.java
Labels: feature

#12 Feat: 소비 내역 조회 API 구현 (전체 조회, 페이징)
  src/main/java/goorm/coutfit/point/controller/PointController.java
  src/main/java/goorm/coutfit/point/controller/response/PointSpendingHistoryResponse.java
  src/main/java/goorm/coutfit/point/domain/PaymentHistory.java
  src/main/java/goorm/coutfit/point/repository/PaymentHistoryRepository.java
  src/main/java/goorm/coutfit/point/service/PointService.java
Labels: feature

#13 Feat: 포인트 충전 API 구현
  src/main/java/goorm/coutfit/point/controller/PointController.java
  src/main/java/goorm/coutfit/point/controller/request/PointChargeRequest.java
  src/main/java/goorm/coutfit/point/controller/response/PointChargeResponse.java
  src/main/java/goorm/coutfit/point/domain/ChargeHistory.java
  src/main/java/goorm/coutfit/point/domain/Point.java
  src/main/java/goorm/coutfit/point/repository/ChargeHistoryRepository.java
  src/main/java/goorm/coutfit/point/service/PointService.java
Labels: feature

#14 Feat: 가맹점 상세 조회 API 구현
  src/main/java/goorm/coutfit/store/controller/StoreController.java
  src/main/java/goorm/coutfit/store/domain/Store.java
  src/main/java/goorm/coutfit/store/domain/StoreImage.java
  src/main/java/goorm/coutfit/store/dto/DiscountResponse.java
  src/main/java/goorm/coutfit/store/dto/StoreDetailResponse.java
  src/main/java/goorm/coutfit/store/repository/StoreRepository.java
  src/main/java/goorm/coutfit/store/service/StoreService.java
Labels: feature

#21 Fix: 가맹점 할인 수정
  src/main/java/goorm/coutfit/store/domain/Store.java
  src/main/java/goorm/coutfit/store/repository/StoreDiscountRepository.java
  src/main/java/goorm/coutfit/store/service/StoreService.java
Labels: bug

#22 Feat: 홈화면 인기 가맹점 목록 조회 API 구현
  src/main/java/goorm/coutfit/point/repository/PaymentHistoryRepository.java
  src/main/java/goorm/coutfit/store/controller/HomeController.java
  src/main/java/goorm/coutfit/store/dto/PopularStoreResponse.java
  src/main/java/goorm/coutfit/store/service/HomeService.java
Labels: feature

#26 Feat: 업종별 소비패턴 분석 API 구현
  src/main/java/goorm/coutfit/point/controller/StatisticsController.java
  src/main/java/goorm/coutfit/point/controller/response/SpendingPatternResponse.java
  src/main/java/goorm/coutfit/point/repository/PaymentHistoryRepository.java
  src/main/java/goorm/coutfit/point/service/StatisticsService.java
Labels: feature

#27 feat: configure CORS for frontend integration
  src/main/java/goorm/coutfit/config/SecurityConfig.java
Labels: chore

#28 Feat: 가맹점 검색 API 구현 (ngram parser)
  src/main/java/goorm/coutfit/store/dto/StoreResponse.java
  src/main/java/goorm/coutfit/store/dto/StoreWithDistance.java
  src/main/java/goorm/coutfit/store/projection/StoreWithDistanceProjection.java
  src/main/java/goorm/coutfit/store/repository/StoreRepository.java
  src/main/java/goorm/coutfit/store/repository/StoreSearchRepository.java
  src/main/java/goorm/coutfit/store/service/StoreService.java
Labels: feature
